import os

WEAVIATE_CLIENT_URL = ""
WEAVIATE_API_KEY = os.environ["WEAVIATE_API_KEY"]

MONGODB_URL = os.environ["MONGODB_URL"]
MONGODB_DB = 'ai-server'
MONGODB_COLLECTION = 'prompts'

OPENAI_API_KEY = os.environ['OPENAI_API_KEY']